web:
  build: .
  links:
    - api
  restart: always
  ports:
    - "8080:8080"
  environment:
    NODE_ENV: production
    API_SERVICE_URL: http://0.0.0.0:3000/
    DROPBOX_UPLOAD_URL: 123
    DROPBOX_UPLOAD_PATH: 123
    DROPBOX_DELETE_URL: 123
    DROPBOX_TOKEN: 123

api:
  image: danieloliv/healthylife-api
  restart: always
  ports:
    - "3000:3000"
  links:
    - db
  environment:
    RAILS_ENV: development
    DATABASE_HOST: db
    DATABASE_PORT: 5432
    gmail_username: example@org.com #substituir pelo endereço de email @gmail.com
    gmail_password: pwd #substituir pela senha do gmail

db:
  image: postgres
  volumes:
    - /var/data/postgres:/var/lib/postgresql/data
